### ISSUE TITLE
Go packages for Docker client throwing an error on go get / go build

### ISSUE THREAD

**Issue by dougbtv** [redhat-nfvpe/koko#22]
Just an FYI that this isn't necessarily a glitch with koko, but, with the dependencies. 

On a fresh CentOS 7 install (from cloud image), with just a `yum install -y golang git`, I go ahead and clone the koko code @ master HEAD, and then try to get the deps...

```
[root@koko1 centos]# mkdir -p /home/centos/gocode/src
[root@koko1 centos]# export GOPATH=/home/centos/gocode/
[root@koko1 centos]# git clone https://github.com/redhat-nfvpe/koko.git $GOPATH/src/koko
```

And at the point where I go to fetch the dependencies, I wind up with this error:

```
[root@koko1 centos]# go get koko
gocode/src/github.com/docker/docker/client/hijack.go:15:2: no buildable Go source files in /home/centos/gocode/src/github.com/docker/docker/pkg/tlsconfig
```

I'm looking for a work-around, not finding a lot of other references to the issue out in the wild.

Also, I can re-create the error stand-alone, that is with:

```
[root@koko1 doug]# cat doug.go 
package main

import (
  "github.com/docker/docker/client"
)


function main() {
	client = "123"
}

[root@koko1 doug]# go build
../github.com/docker/docker/client/hijack.go:15:2: no buildable Go source files in /home/centos/gocode/src/github.com/docker/docker/pkg/tlsconfig
```

**Comment by s1061123** [comment]
Doug,

Thank you for your input!
Let me check the code and try to find the workaround.

**Comment by s1061123** [comment]
@dougbtv 
At following commit, moby(a.k.a. docker) gives up to build it in go1.6.x that is used in CentOS default (1.6.3)
https://github.com/moby/moby/commit/6bfd0f6b5d08bcd609da11947432ad0f3aa3d8fd

Actually moby uses several API (e.g. http.ErrUseLastResponse) that is introduced at golang 1.7+, so far koko does support golang 1.6 no longer.

Can you install latest go lang (at least 1.7+) with third party repo, like following?
http://go-repo.io/

I've changed README.md to indicate it. Thank you for your pointing out, Doug!

**Comment by dougbtv** [comment]
Thanks for figuring out that one, appreciate it! Definitely no problem to
use go 1.7+
