### ISSUE TITLE
Add cleanup procedure in case of error

### ISSUE THREAD

**Issue by networkop** [redhat-nfvpe/koko#42]
Add cleanup procedure in case of error for clean bailout.

============== Original post (Concurrent calls to MakeVeth) ===============
Hi Tomofumi,
I'm using koko_api to setup links between containers based on some special logic. I'm running into a problem when MakeVeth gets called twice (once for each container in a pair) and one of them inevitably ends up with an interface with tempLinkName. This is what I believe is happening
T0: there are two calls to MakeVeth with the same parameters
T1: GetVethPair creates interfaces inside containers with tempLinkNames
T2: SetVethLink updates interface names from the first MakeVeth call
T3: the second SetVethLink call fails to rename interface since it already exists from the first call

Is there a standard way of dealing with this in koko_api ? The only option I see so far is to write my own MakeVeth function that is not going to skip the tempLinkNames and go straight to real interface names. I just don't fully understand what was the purpose of tempLinkName...

**Comment by s1061123** [comment]
Hi @networkop , thank you for your question.

I am not clear that the two MakeVeth() call with same arguments because we cannot create interface with same name in a container.
Could you please let me know the detail (if possible, why you need to create same interface and so on...

BTW, the reason why I need to create veth with tempLinkName is to avoid ifname overlapping with host.
e.g.
 1) there is an interface, "testIF1" in container host (not container).
 2) create container, "container1"
 3) try to add "testIF1" to "container1" with koko. Koko first creates interface at host and then move it to container, hence koko is failed to create interface, "testIF1" because of overlap in host side.

**Comment by networkop** [comment]
Ah, now the templinkName makes sense.
What I have is a datastructure that describes how to connect containers. there's one such datastructure for each container and it contains parameters (container name and link name) for both sides of the link. this works nicely for vxlan, since each side of the link is created independently. but with veth pair it's tricky, mainly because i cannot know which container (of the pair) is going to come up first or if they come up at the same time. so when, e.g. c1 comes up, i read his link datastructure and determine that he needs to connect to c2. the same happens for c2. if c1 comes up before c2, everything works fine since i check if c2 is alive and if not I go on, assuming c2 will connect the link later. but if c1 and c2 come up at the same time, that's when they both try to MakeVEth with the same parameters.

I'm thinking,  would it make sense to add a cleanup procedure in MakeVeth so that in case setveth fails to change interface name inside container because it already exists, it then removes the veth with templinknames so that they are not left hanging?

**Comment by networkop** [comment]
Thanks, I've actually seen ratchet already. I think Doug assumes that both containers are up already and so he only makes a single MakeVeth call. I'm also building my own CNI plugin and I'm not sure if it's a safe assumption to make that both containers are going to come up simultaneously, since it's up to a scheduler to decide. So my base assumption is that they will not be up at the same time, therefore I'm trying to create a veth link for each container, which works, but leaves that tempLinkName interface hanging in one of the containers.

That's fine, there's an easy workaround for that - just predictably pick one of the containers and create a veth link just from his perspective.

But having some cleanup procedure would be really cool, since this would make the api.MakeVeth() idempotent.

**Comment by s1061123** [comment]
Closed due to #43 adds cleanup code.
