### ISSUE TITLE
sandboxkey vs net namespace?

### ISSUE THREAD

**Issue by dougbtv** [redhat-nfvpe/koko#7]
https://github.com/dougbtv/ratchet-cni/blob/master/vendor/github.com/redhat-nfvpe/koko/koko.go#L344

I'll make a further note later, but, sandboxkey wasn't working for me under kubernetes

**Comment by dougbtv** [comment]
```
[centos@kubecni-master ~]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:22:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
[centos@kubecni-master ~]$ cat /etc/redhat-release 
CentOS Linux release 7.3.1611 (Core) 

```

**Comment by dougbtv** [comment]
my notes from slack chat.


```
Stuck in a bit of a spot trying to use `GetNS()` in the CNI ns Go package between testing with the `./scripts/docker-run.sh` (from the CNI repo) and then running later in Kubernetes.

Somehow, when I run with `docker-run.sh` script, the mapped container (with that script, a busybox instance)  has a netns with a file system type of proc, e.g. it looks like:

```[centos@cni ~]$ sudo stat -f /var/run/docker/netns/bb03347a44ec | grep "Type"
    ID: 0        Namelen: 255     Type: proc
```

But, when I run in kubernetes -- the type is `tmpfs` for the infra container (which I would've otherwise assumed to have been fairly similar to the mapped container network), and it looks like this in Kube:

```[centos@kubecni-minion-1 ~]$ sudo stat -f /var/run/docker/netns/96a925540e71 | grep Type
    ID: 0        Namelen: 255     Type: tmpfs
```

Which is causing me fits when I run the cni/ns package's `GetNS()` method, because it calls `IsNSorErr()` which in turn checks the filesystem type, allowing proc, but not tmpfs. I tried to hack it and say "ok, well, allow tmpfs" but, that apparently didn't get me much further. (I then later pull a file descriptor out of the result of `GetNS()`, and use it to link containers with a veth connection, using `LinkByName()` in `vishvananda/netlink` which appears to fail if `IsNSorErr()` returns an error)

Any idea why it's different between the two? Is that configurable in Kube? (edited)

dougbtv [3:48 PM] 
so, yeah... turns oooout.... Maybe in kube (or this version of docker in kube? or what) that when I look at `/var/run/docker/netns/96a925540e71` -- which I get from docker client go library (effectively looking at `docker inspect`) -- that... that is a lie. If I look at `/proc/$pid_of_container/net/ns` -- that's the real mccoy, and has a `Type: proc` in `stat -f`
```

**Comment by s1061123** [comment]
done.
